### ISSUE TITLE
Security vulnerabilities reported by GitHub

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sharedb-ace-backend#2]
source-academy/sharedb-ace-backend
--
Known high severity security vulnerability detected in lodash < 4.17.13 defined in package-lock.json.package-lock.json update suggested: lodash ~> 4.17.13. | Known high severity security vulnerability detected in lodash < 4.17.13 defined in package-lock.json. | package-lock.json update suggested: lodash ~> 4.17.13.
Known high severity security vulnerability detected in lodash < 4.17.13 defined in package-lock.json.
package-lock.json update suggested: lodash ~> 4.17.13.

source-academy/sharedb-ace-backend
--
Known high severity security vulnerability detected in lodash < 4.17.13 defined in yarn.lock.yarn.lock update suggested: lodash ~> 4.17.13. | Known high severity security vulnerability detected in lodash < 4.17.13 defined in yarn.lock. | yarn.lock update suggested: lodash ~> 4.17.13.
Known high severity security vulnerability detected in lodash < 4.17.13 defined in yarn.lock.
yarn.lock update suggested: lodash ~> 4.17.13.

**Comment by jiayushe** [comment]
I have bumped lodash to 4.17.14.
