### ISSUE TITLE
Another vulnerability, also found by Github

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sharedb-ace-backend#3]
source-academy/sharedb-ace-backend
--
Known high severity security vulnerability detected in ws >= 0.2.6, < 3.3.1defined in yarn.lock.yarn.lock update suggested: ws ~> 3.3.1. | Known high severity security vulnerability detected in ws >= 0.2.6, < 3.3.1defined in yarn.lock. | yarn.lock update suggested: ws ~> 3.3.1.
Known high severity security vulnerability detected in ws >= 0.2.6, < 3.3.1defined in yarn.lock.
yarn.lock update suggested: ws ~> 3.3.1.

**Comment by jiayushe** [comment]
I have bumped ws to 7.0.1.
